python train.py  \
--data-dir /home/zack/Data/paperrescaledLITS/ \
--data-list /home/zack/Data/LITS/dataset/train.txt \
--val-data-list /home/zack/Data/LITS/dataset/val.txt \
--snapshot-dir './snapshots/HanResNet5Slices' \
--gpu-mask '0,1' \
--learning-rate 1e-3 \
--input-size '512,512' \
--random-scale \
--random-mirror \
--num-steps 237910 \