python train.py  \
--data-dir /home/zack/Data/paperrescaledLITS/ \
--data-list /home/zack/Data/paperrescaledLITS/dataset/train.txt \
--val-data-list /home/zack/Data/paperrescaledLITS/dataset/val.txt \
--restore-from './snapshots/HanResNet' \
--snapshot-dir './snapshots/HanResNet' \
--gpu-mask '0,1' \
--learning-rate 2.0e-4 \
--random-scale \
--random-mirror \
--num-steps 300000 \
